<?php

namespace GestionBundle\Repository;

/**
 * AlumnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumnoRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAlumnosList() { 
	    return $this->createQueryBuilder('a')
	    			->orderBy('a.apellido')
	    			->addOrderBy('a.nombre')
			        ->getQuery()
			        ->getResult(); 
	} 
}
